name: CI/CD Recommender System

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.MINIO_ACCESS_KEY }}" ]; then
            echo "MINIO_ACCESS_KEY is EMPTY"
            exit 1
          else
            echo "MINIO_ACCESS_KEY exists"
          fi
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Lint
        run: poetry run ruff check .

  train:
    name: Train model & log to MLflow
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install poetry

      - run: |
          poetry config virtualenvs.create false
          poetry install
      - name: Configure DVC remotes
        run: |
          dvc remote modify myremote access_key_id ${{ secrets.MINIO_ACCESS_KEY }}
          dvc remote modify myremote secret_access_key ${{ secrets.MINIO_SECRET_KEY }}
          dvc remote modify myremote endpointurl ${{ secrets.MINIO_ENDPOINT }}
      
          dvc remote modify models_storage access_key_id ${{ secrets.MINIO_ACCESS_KEY }}
          dvc remote modify models_storage secret_access_key ${{ secrets.MINIO_SECRET_KEY }}
          dvc remote modify models_storage endpointurl ${{ secrets.MINIO_ENDPOINT }}

      - name: Pull dataset
        run: |
          dvc remote default myremote
          dvc pull

      - name: Train model
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}

        run: poetry run python src/recommender_system/presentation/train.py

      - name: Quality Gate
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: poetry run python scripts/quality_gate.py


  build:
    name: Build Docker images locally
    runs-on: self-hosted
    needs: train

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build API image
        run: |
          docker build -f Dockerfile.api \
            -t recsys-api:latest .

      - name: Build Worker image
        run: |
          docker build -f Dockerfile.worker \
            -t recsys-worker:latest .
